name: myfinance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  fl_chart: ^0.55.2 
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  image_picker: ^1.1.2
  provider: ^6.0.0
  shared_preferences: ^2.5.2
  syncfusion_flutter_charts: ^28.2.12
  timezone: ^0.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/allassets/
    - assets/default_images/
